import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { DM_Sans } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { repositoryName } from "@/prismicio";
import { PrismicPreview } from "@prismicio/next";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body className='grid bg-[#070815] text-white'>
      <Header/>
      <main>
        {children}
      </main>
      <Footer/>
      <PrismicPreview repositoryName={repositoryName}/>
      </body>
    </html>
  );
}
